/* eslint-disable prettier/prettier */
// material
import { Box, Container, Typography } from '@material-ui/core';

// ----------------------------------------------------------------------

// ----------------------------------------------------------------------

export default function LandingStake() {
  return (
    <Container
      maxWidth="lg"
      sx={{
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '0px !important',
        margin: '0 auto',
        marginTop: { md: '80px !important', xs: '40px' },
        marginBottom: '40px !important'
      }}
    >
      <Box>
        <Typography
          component="p"
          variant="overline"
          sx={{
            textTransform: 'none',
            margin: '0 auto',
            marginBottom: 2,
            color: 'common.black',
            display: 'block',
            fontFamily: 'Montserrat',
            fontWeight: 600,
            fontSize: { xs: 28, md: 64 },
            lineHeight: '72px',
            letterSpacing: 0
          }}
        >
          Circular Economy
        </Typography>
      </Box>
      <Box>
        <Typography
          component="p"
          sx={{
            padding: '20px',
            marginBottom: 4,
            textTransform: 'none',
            color: '#7C7B7B',
            display: 'block',
            fontFamily: 'Poppins',
            fontWeight: 400,
            fontSize: 16,
            lineHeight: '28px',
            opacity: 0.6,
            margin: { xs: 'auto', md: 'auto auto 32px auto' }
          }}
        >
          All fees generated by the protocol are returned to the community through buybacks, airdrops or increases in
          the liquidity pools
        </Typography>
      </Box>
      <Box style={{ width: '100%' }}>
        <Box component="img" alt="light mode" src="/static/home/economy.png" sx={{ margin: '0 auto', width: '100%' }} />
      </Box>
    </Container>
  );
}
